services:
  db:
    image: postgres:alpine
    ports:
      - "5432:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./docker-volumes/db:/var/lib/postgresql/data
